### ISSUE TITLE
Mod Settings Menu has "testtesttest" string everywhere

### ISSUE THREAD

**Issue by sb0** [jackhumbert/mod_settings#1]
First of all, thank you for making all your mods.
On behalf of the community we greatly appreciate your efforts and are ever grateful.

For some reason, when I go to Mod Settings menu all I see is strings that say "testtesttest"
See screenshot below.

Any ideas to help me troubleshoot ?

![20220825012353_2](https://user-images.githubusercontent.com/2439976/186964763-1b80ee5c-67ad-4e76-9b8d-0e0524a3e6df.jpg)

**Comment by jackhumbert** [comment]
I think this only happens if there aren't any mods that use it. Does it go away once you install one?

**Comment by sb0** [comment]
Hi There, Thanks for your reply!

This was before the 1.6 update and I had only _let there be flight installed_.

Once let there be flight is ready for 1.6 I will try again and report back.
As of now I do not have the issue because I have in-world navigation installed.

**Comment by sb0** [comment]
This is working fine now after 1.6 updates.
Closing this issue.
Thanks again.
