### ISSUE TITLE
Ingame Character page not showing

### ISSUE THREAD

**Issue by Kbessingu** [jackhumbert/mod_settings#18]
If your aware of this bug feel free to delete. After installing [v0.2.1-preview-1 for 2.01] (https://github.com/jackhumbert/mod_settings/releases/tag/v0.2.1-preview-1) the character page is a blank page 
![with Mod settings installed](https://github.com/jackhumbert/mod_settings/assets/147370810/66dd45d1-c19a-4fa1-bf50-f138c725fe46)
I installed both mod settings v0.2.1-preview-1 pdb and mod settings v0.2.1-preview-1
removing mod settings brings back it back
thanks for the mod ^^

**Comment by Spueh** [comment]
can confirm

**Comment by SpudmanWP** [comment]
The solution is simple as you only need the Mod_Settings mod to change the settings.  

1. Load Mod_Settings
2. Start Game to main menu only
3. Changes settings under "Mod Settings"
4. Exit game
5. Unload Mod_Settings
6. Restart game

**Comment by jackhumbert** [comment]
Fixed in preview-3
