### ISSUE TITLE
Unable to "sleep" in apartment with mod enabled

### ISSUE THREAD

**Issue by Amoeba00** [jackhumbert/mod_settings#4]
Installed latest mod (.3, which now works in v1.6) - but now the "sleep" menu no longer appears when in the apartments (in any of them)  when trying to sleep (for the XP bonus timer).

The game appears to lock up, since you get a blank screen with the base background, but you can still get to your inventory and get out of bed.

Disabling this mod only, results in the sleep timer appearing.

Prior to v1.6 - there was no issue - but now in 1.6 you get an option to select how many hours you want to sleep - whereas previously it was a fixed amount with no screen to interact.

**Comment by jackhumbert** [comment]
Fixed in [8e13b6c](https://github.com/jackhumbert/mod_settings/commit/8e13b6c745e7df15aa2c9f21ea5bb4a5f562b542) / v0.0.4

**Comment by Amoeba00** [comment]
Just wanted to say thanks for the quick turn around.  Have a great week!
