### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by Adamqu** [jackhumbert/mod_settings#5]
hello i have a problem with my installation i already tried everything and the mod either doesnt work or i get this  i watched videos how to install i read the tutorials  i dont know what to do anymore [](url)
![bug cyberpunk](https://user-images.githubusercontent.com/113313899/189550106-2df5cba8-b33f-489d-af37-6be76c89ac21.png)
[let_there_be_flight.log](https://github.com/jackhumbert/mod_settings/files/9543599/let_there_be_flight.log)
[Cyberpunk2077 log dmp file.zip](https://github.com/jackhumbert/mod_settings/files/9543600/Cyberpunk2077.log.dmp.file.zip)

**Comment by jackhumbert** [comment]
This repo is for Mod Settings, not LTBF.
