### ISSUE TITLE
Mod name max length + Modules

### ISSUE THREAD

**Issue by p-marques** [jackhumbert/mod_settings#6]
# Mod name length limitation
It may be worth warning mod authors of a potential issue with the length of the class that contain the settings.
Example:
```ini
[EddiesReceivedMult.Menu.ERMMenuSettings]
IsEnabled = true
EddiesMultiplier = 2.000000
ShowDebugMsg = false
DebugMsgDuration = 8.000000
```
```ini
[EddiesReceivedMult.Menu.EddiesReceivedMultSettings]
IsEnabled = true
EddiesMultiplier = 2.000000
ShowDebugMsg = false
DebugMsgDuration = 8.000000
```
The first snippet works, the second causes a reset of the settings every time the game loads. The max length at which it still works appears to be 49.

This isn't a big issue, but if people are declaring redscript modules, names can get pretty big.

# Redscript modules and conditional compilation

It would be awesome if the redscript files of "Mod Settings" declared a module header. This would allow mod authors to easily support this mod without requiring it. This can be achieved now but only by separating the core mod file(s) from the menu stuff, but it would be awesome to just do `@if(ModuleExists("ModSettings"))` or something.

Anyway, just some thoughts. Thank you for the work you've put into this.

**Comment by jackhumbert** [comment]
This may be related to #7 - I just added a module declaration of `ModSettingsModule`, so we can do something like this per mod:

```swift
@if(ModuleExists("ModSettingsModule")) 
public func LTBF_RegisterListener(listener: ref<IScriptable>) {
  ModSettings.RegisterListenerToClass(this);
}

@if(!ModuleExists("ModSettingsModule")) 
public func LTBF_RegisterListener(listener: ref<IScriptable>) { }
```

Each mod would need to define their own uniquely named function like this, which can be called anywhere. Doing it this way prevents having to create two conditional compilation wrappers for each method the `RegisterListenerClass` method is called from. Do you think this would work for what you'd need?

**Comment by p-marques** [comment]
Thank you for the module declarations. I was already using conditional compilation to achieve the goal, which was to support Mod Settings without making it a requirement, but now this because simpler.

---

The max length "issue" I believe is a INIReader thing.
```c++
#define MAX_SECTION 50
```

I think this const is what's limiting the section name. This is causing the section to be ignored when reading and, as expected, Mod Settings reacts as if it has never seen the menu with the really long name and writes the default values. At least this is my best guess.

However, I recommend you don't try to 'fix' this limitation and simply warn mod makers. 49 is enough :)

I'm closing this issue. Thank you.

**Comment by jackhumbert** [comment]
Ah, good catch! I don't think there's any down side to increasing it - I've gone ahead and bumped it up to 1024 chars, along with increasing some of the other defaults that may cause issues down the road. I'll add these limits to the readme as well. Thanks for digging into things!
