### ISSUE TITLE
1.61 Compatability

### ISSUE THREAD

**Issue by WouldBeForestHermit** [jackhumbert/mod_settings#8]
There seems to be compatiblity issues with this mod and the new patch 1.61

**Comment by GarnetSunset** [comment]
Running the latest build and "mod settings" does not appear in my pause menu

**Comment by lvanlo** [comment]
still not working from 0.0.8

**Comment by WeirdScience06** [comment]
I have double-checked the install, but I don't have mod settings appear. 

I can't see any issues in the log files

**Comment by HyPeRXKo** [comment]
After the v.0.09, it's working fine for me!

**Comment by WouldBeForestHermit** [comment]
Seconded, 0.0.9 is working for me.
